name: Secuencial jobs
on:
  push:
    branches: [ feature/add-repo ]
  pull_request:
    branches: [ feature/add-repo ]
jobs:
  release:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          npm i
          npm run build

      - name: publish
        run: npm run publish


  buildStorybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create artifact Storybook
        run: |
          npm i
          npm run build-storybook
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
        
